version: '3.7'
services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    container_name: backend
    depends_on:
      - solr
    networks:
      - solr
    hostname: backend

  web:
    build: ./web-app
    ports:
      - 3000:3000
    container_name: web
    depends_on:
      - solr
      - backend
    networks:
      - solr
    hostname: web

  caddy:
    build: ./caddy
    ports:
      - 80:80
    container_name: caddy
    depends_on:
      - backend
      - web
    networks:
      - solr
    hostname: caddy

  solr:
    image: solr:9.0
    container_name: solr
    ports:
     - "8983:8983"
    environment:
      - ZK_HOST=zoo:2181,zoo2:2181,zoo3:2181
    networks:
      - solr
    depends_on:
      - zoo
    volumes:
      - solr_volume:/var/solr
    hostname: solr

  zoo:
    image: zookeeper:3.8
    container_name: zoo
    restart: always
    hostname: zoo
    ports:
      - 2181:2181
      - 7000:7000
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo:2888:3888;2181 
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr
  
networks:
  solr:

volumes:
  solr_volume: